title:              GEMP
email:              gemp.usp@gmail.com
description:        Grupo de Estudos de Magnetosfera e Plasmas
author:             GEMP
baseurl:            "/gemp-usp"
url:                "https://gemp-usp.github.io/"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    gemp-usp
#facebook_username:  StartBootstrap
#instagram_username:  gempusp
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-H5H3098P7T # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
